version: '3'

services:
  db:
    container_name: db
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGDB_DATABASE: 'task_mern'
    volumes:
      - ./mongo:/data/db
